repos:
- repo: https://gitlab.santanderbr.corp/cpf/pre-commit
  rev: v1.50.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
    - id: terraform_validate
    - id: terraform_tfsec
    - id: checkov